name: Panilla
version: ${version}
main: com.ruinscraft.panilla.bukkit.PanillaPlugin
api-version: 1.21.4
folia-supported: true
author: ds58
description: Prevent abusive NBT and harmful packets
website: https://github.com/Ruinscraft/Panilla
permissions:
  panilla.log.chat:
    description: View warning logs in chat if enabled in the config
    default: op
  panilla.bypass:
    description: Bypass packet checks
    default: op